artifacts_root: artifacts

prepare_vgg_model:
  root_dir: artifacts/prepare_vgg_model
  vgg_model_path: artifacts/prepare_vgg_model/vgg16.h5

prediction:
  tokenizer: ../drive/MyDrive/Img-Cap/Project/artifacts/tokenizer.p
  drive_fold: drive/MyDrive/Img-Cap/
  model: ../drive/MyDrive/Img-Cap/Project/artifacts/model.h5